using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using System.Runtime.Intrinsics.Arm;

namespace SortingNetworks;

// <auto-generated>
// This file was generated by generate_unrolled.cs
// Do not edit manually.
// </auto-generated>

/// <summary>
/// Provides sorting-network-based sorting for small collections.
/// Uses fixed compare-and-swap networks for sizes up to 28, including
/// depth-13 networks for 27 and 28 channels from arXiv:2511.04107.
/// Falls back to the default .NET sort for larger inputs.
/// </summary>
public static partial class NetworkSort
{
    /// <summary>
    /// Sorts a span of byte using a sorting network when possible.
    /// </summary>
    public static void Sort(Span<byte> span)
    {
        int n = span.Length;
        if (n == 27 || n == 28)
        {
            if (Avx2.IsSupported)
            {
                if (n == 27)
                    SortSimd27(span);
                else
                    SortSimd28(span);
                return;
            }

            if (Ssse3.IsSupported || AdvSimd.IsSupported)
            {
                if (n == 27)
                    SortSimd128_27(span);
                else
                    SortSimd128_28(span);
                return;
            }

            ref byte first = ref MemoryMarshal.GetReference(span);
            if (n == 27)
                Sort27(ref first);
            else
                Sort28(ref first);
            return;
        }

        span.Sort();
    }

    /// <summary>
    /// Sorts an array of byte using a sorting network when possible.
    /// </summary>
    public static void Sort(byte[] array)
    {
        ArgumentNullException.ThrowIfNull(array);
        Sort(array.AsSpan());
    }

    /// <summary>
    /// Sorts a span of byte using a sorting network when possible,
    /// with a custom comparer.
    /// </summary>
    public static void Sort(Span<byte> span, IComparer<byte>? comparer)
    {
        comparer ??= Comparer<byte>.Default;
        int n = span.Length;
        if (n == 27 || n == 28)
        {
            ApplyNetworkWithComparer(span, NetworkData.GetNetwork(n), comparer);
            return;
        }

        span.Sort(comparer);
    }

    /// <summary>
    /// Sorts an array of byte using a sorting network when possible,
    /// with a custom comparer.
    /// </summary>
    public static void Sort(byte[] array, IComparer<byte>? comparer)
    {
        ArgumentNullException.ThrowIfNull(array);
        Sort(array.AsSpan(), comparer);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void ApplyNetworkWithComparer(Span<byte> span, int[] network, IComparer<byte> comparer)
    {
        ref byte first = ref MemoryMarshal.GetReference(span);
        for (int i = 0; i < network.Length; i += 2)
        {
            ref byte a = ref Unsafe.Add(ref first, network[i]);
            ref byte b = ref Unsafe.Add(ref first, network[i + 1]);
            if (comparer.Compare(a, b) > 0)
            {
                byte temp = a;
                a = b;
                b = temp;
            }
        }
    }

    /// <summary>
    /// Sorts a span of sbyte using a sorting network when possible.
    /// </summary>
    public static void Sort(Span<sbyte> span)
    {
        int n = span.Length;
        if (n == 27 || n == 28)
        {
            if (Avx2.IsSupported)
            {
                if (n == 27)
                    SortSimd27_sbyte(span);
                else
                    SortSimd28_sbyte(span);
                return;
            }

            if (Ssse3.IsSupported || AdvSimd.IsSupported)
            {
                if (n == 27)
                    SortSimd128_27_sbyte(span);
                else
                    SortSimd128_28_sbyte(span);
                return;
            }

            ref sbyte first = ref MemoryMarshal.GetReference(span);
            if (n == 27)
                Sort27(ref first);
            else
                Sort28(ref first);
            return;
        }

        span.Sort();
    }

    /// <summary>
    /// Sorts an array of sbyte using a sorting network when possible.
    /// </summary>
    public static void Sort(sbyte[] array)
    {
        ArgumentNullException.ThrowIfNull(array);
        Sort(array.AsSpan());
    }

    /// <summary>
    /// Sorts a span of sbyte using a sorting network when possible,
    /// with a custom comparer.
    /// </summary>
    public static void Sort(Span<sbyte> span, IComparer<sbyte>? comparer)
    {
        comparer ??= Comparer<sbyte>.Default;
        int n = span.Length;
        if (n == 27 || n == 28)
        {
            ApplyNetworkWithComparer(span, NetworkData.GetNetwork(n), comparer);
            return;
        }

        span.Sort(comparer);
    }

    /// <summary>
    /// Sorts an array of sbyte using a sorting network when possible,
    /// with a custom comparer.
    /// </summary>
    public static void Sort(sbyte[] array, IComparer<sbyte>? comparer)
    {
        ArgumentNullException.ThrowIfNull(array);
        Sort(array.AsSpan(), comparer);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void ApplyNetworkWithComparer(Span<sbyte> span, int[] network, IComparer<sbyte> comparer)
    {
        ref sbyte first = ref MemoryMarshal.GetReference(span);
        for (int i = 0; i < network.Length; i += 2)
        {
            ref sbyte a = ref Unsafe.Add(ref first, network[i]);
            ref sbyte b = ref Unsafe.Add(ref first, network[i + 1]);
            if (comparer.Compare(a, b) > 0)
            {
                sbyte temp = a;
                a = b;
                b = temp;
            }
        }
    }

    /// <summary>
    /// Sorts a span of short using a sorting network when possible.
    /// </summary>
    public static void Sort(Span<short> span)
    {
        int n = span.Length;
        if (n == 27 || n == 28)
        {
            if (Avx512BW.IsSupported)
            {
                if (n == 27)
                    SortSimd27_short(span);
                else
                    SortSimd28_short(span);
                return;
            }

            if (AdvSimd.Arm64.IsSupported)
            {
                if (n == 27)
                    SortSimdArm27_short(span);
                else
                    SortSimdArm28_short(span);
                return;
            }

            ref short first = ref MemoryMarshal.GetReference(span);
            if (n == 27)
                Sort27(ref first);
            else
                Sort28(ref first);
            return;
        }

        span.Sort();
    }

    /// <summary>
    /// Sorts an array of short using a sorting network when possible.
    /// </summary>
    public static void Sort(short[] array)
    {
        ArgumentNullException.ThrowIfNull(array);
        Sort(array.AsSpan());
    }

    /// <summary>
    /// Sorts a span of short using a sorting network when possible,
    /// with a custom comparer.
    /// </summary>
    public static void Sort(Span<short> span, IComparer<short>? comparer)
    {
        comparer ??= Comparer<short>.Default;
        int n = span.Length;
        if (n == 27 || n == 28)
        {
            ApplyNetworkWithComparer(span, NetworkData.GetNetwork(n), comparer);
            return;
        }

        span.Sort(comparer);
    }

    /// <summary>
    /// Sorts an array of short using a sorting network when possible,
    /// with a custom comparer.
    /// </summary>
    public static void Sort(short[] array, IComparer<short>? comparer)
    {
        ArgumentNullException.ThrowIfNull(array);
        Sort(array.AsSpan(), comparer);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void ApplyNetworkWithComparer(Span<short> span, int[] network, IComparer<short> comparer)
    {
        ref short first = ref MemoryMarshal.GetReference(span);
        for (int i = 0; i < network.Length; i += 2)
        {
            ref short a = ref Unsafe.Add(ref first, network[i]);
            ref short b = ref Unsafe.Add(ref first, network[i + 1]);
            if (comparer.Compare(a, b) > 0)
            {
                short temp = a;
                a = b;
                b = temp;
            }
        }
    }

    /// <summary>
    /// Sorts a span of ushort using a sorting network when possible.
    /// </summary>
    public static void Sort(Span<ushort> span)
    {
        int n = span.Length;
        if (n == 27 || n == 28)
        {
            if (Avx512BW.IsSupported)
            {
                if (n == 27)
                    SortSimd27_ushort(span);
                else
                    SortSimd28_ushort(span);
                return;
            }

            if (AdvSimd.Arm64.IsSupported)
            {
                if (n == 27)
                    SortSimdArm27_ushort(span);
                else
                    SortSimdArm28_ushort(span);
                return;
            }

            ref ushort first = ref MemoryMarshal.GetReference(span);
            if (n == 27)
                Sort27(ref first);
            else
                Sort28(ref first);
            return;
        }

        span.Sort();
    }

    /// <summary>
    /// Sorts an array of ushort using a sorting network when possible.
    /// </summary>
    public static void Sort(ushort[] array)
    {
        ArgumentNullException.ThrowIfNull(array);
        Sort(array.AsSpan());
    }

    /// <summary>
    /// Sorts a span of ushort using a sorting network when possible,
    /// with a custom comparer.
    /// </summary>
    public static void Sort(Span<ushort> span, IComparer<ushort>? comparer)
    {
        comparer ??= Comparer<ushort>.Default;
        int n = span.Length;
        if (n == 27 || n == 28)
        {
            ApplyNetworkWithComparer(span, NetworkData.GetNetwork(n), comparer);
            return;
        }

        span.Sort(comparer);
    }

    /// <summary>
    /// Sorts an array of ushort using a sorting network when possible,
    /// with a custom comparer.
    /// </summary>
    public static void Sort(ushort[] array, IComparer<ushort>? comparer)
    {
        ArgumentNullException.ThrowIfNull(array);
        Sort(array.AsSpan(), comparer);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void ApplyNetworkWithComparer(Span<ushort> span, int[] network, IComparer<ushort> comparer)
    {
        ref ushort first = ref MemoryMarshal.GetReference(span);
        for (int i = 0; i < network.Length; i += 2)
        {
            ref ushort a = ref Unsafe.Add(ref first, network[i]);
            ref ushort b = ref Unsafe.Add(ref first, network[i + 1]);
            if (comparer.Compare(a, b) > 0)
            {
                ushort temp = a;
                a = b;
                b = temp;
            }
        }
    }

    /// <summary>
    /// Sorts a span of int using a sorting network when possible.
    /// </summary>
    public static void Sort(Span<int> span)
    {
        int n = span.Length;
        if (n == 27 || n == 28)
        {
            if (Avx512F.IsSupported)
            {
                if (n == 27)
                    SortSimd27_512_int(span);
                else
                    SortSimd28_512_int(span);
                return;
            }

            if (Avx2.IsSupported)
            {
                if (n == 27)
                    SortSimd27_int(span);
                else
                    SortSimd28_int(span);
                return;
            }

            if (AdvSimd.Arm64.IsSupported)
            {
                if (n == 27)
                    SortSimdArm27_int(span);
                else
                    SortSimdArm28_int(span);
                return;
            }

            ref int first = ref MemoryMarshal.GetReference(span);
            if (n == 27)
                Sort27(ref first);
            else
                Sort28(ref first);
            return;
        }

        span.Sort();
    }

    /// <summary>
    /// Sorts an array of int using a sorting network when possible.
    /// </summary>
    public static void Sort(int[] array)
    {
        ArgumentNullException.ThrowIfNull(array);
        Sort(array.AsSpan());
    }

    /// <summary>
    /// Sorts a span of int using a sorting network when possible,
    /// with a custom comparer.
    /// </summary>
    public static void Sort(Span<int> span, IComparer<int>? comparer)
    {
        comparer ??= Comparer<int>.Default;
        int n = span.Length;
        if (n == 27 || n == 28)
        {
            ApplyNetworkWithComparer(span, NetworkData.GetNetwork(n), comparer);
            return;
        }

        span.Sort(comparer);
    }

    /// <summary>
    /// Sorts an array of int using a sorting network when possible,
    /// with a custom comparer.
    /// </summary>
    public static void Sort(int[] array, IComparer<int>? comparer)
    {
        ArgumentNullException.ThrowIfNull(array);
        Sort(array.AsSpan(), comparer);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void ApplyNetworkWithComparer(Span<int> span, int[] network, IComparer<int> comparer)
    {
        ref int first = ref MemoryMarshal.GetReference(span);
        for (int i = 0; i < network.Length; i += 2)
        {
            ref int a = ref Unsafe.Add(ref first, network[i]);
            ref int b = ref Unsafe.Add(ref first, network[i + 1]);
            if (comparer.Compare(a, b) > 0)
            {
                int temp = a;
                a = b;
                b = temp;
            }
        }
    }

    /// <summary>
    /// Sorts a span of uint using a sorting network when possible.
    /// </summary>
    public static void Sort(Span<uint> span)
    {
        int n = span.Length;
        if (n == 27 || n == 28)
        {
            if (Avx512F.IsSupported)
            {
                if (n == 27)
                    SortSimd27_512_uint(span);
                else
                    SortSimd28_512_uint(span);
                return;
            }

            if (Avx2.IsSupported)
            {
                if (n == 27)
                    SortSimd27_uint(span);
                else
                    SortSimd28_uint(span);
                return;
            }

            if (AdvSimd.Arm64.IsSupported)
            {
                if (n == 27)
                    SortSimdArm27_uint(span);
                else
                    SortSimdArm28_uint(span);
                return;
            }

            ref uint first = ref MemoryMarshal.GetReference(span);
            if (n == 27)
                Sort27(ref first);
            else
                Sort28(ref first);
            return;
        }

        span.Sort();
    }

    /// <summary>
    /// Sorts an array of uint using a sorting network when possible.
    /// </summary>
    public static void Sort(uint[] array)
    {
        ArgumentNullException.ThrowIfNull(array);
        Sort(array.AsSpan());
    }

    /// <summary>
    /// Sorts a span of uint using a sorting network when possible,
    /// with a custom comparer.
    /// </summary>
    public static void Sort(Span<uint> span, IComparer<uint>? comparer)
    {
        comparer ??= Comparer<uint>.Default;
        int n = span.Length;
        if (n == 27 || n == 28)
        {
            ApplyNetworkWithComparer(span, NetworkData.GetNetwork(n), comparer);
            return;
        }

        span.Sort(comparer);
    }

    /// <summary>
    /// Sorts an array of uint using a sorting network when possible,
    /// with a custom comparer.
    /// </summary>
    public static void Sort(uint[] array, IComparer<uint>? comparer)
    {
        ArgumentNullException.ThrowIfNull(array);
        Sort(array.AsSpan(), comparer);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void ApplyNetworkWithComparer(Span<uint> span, int[] network, IComparer<uint> comparer)
    {
        ref uint first = ref MemoryMarshal.GetReference(span);
        for (int i = 0; i < network.Length; i += 2)
        {
            ref uint a = ref Unsafe.Add(ref first, network[i]);
            ref uint b = ref Unsafe.Add(ref first, network[i + 1]);
            if (comparer.Compare(a, b) > 0)
            {
                uint temp = a;
                a = b;
                b = temp;
            }
        }
    }

    /// <summary>
    /// Sorts a span of long using a sorting network when possible.
    /// </summary>
    public static void Sort(Span<long> span)
    {
        int n = span.Length;
        if (n == 27 || n == 28)
        {
            if (Avx512F.IsSupported)
            {
                if (n == 27)
                    SortSimd27_long(span);
                else
                    SortSimd28_long(span);
                return;
            }

            ref long first = ref MemoryMarshal.GetReference(span);
            if (n == 27)
                Sort27(ref first);
            else
                Sort28(ref first);
            return;
        }

        span.Sort();
    }

    /// <summary>
    /// Sorts an array of long using a sorting network when possible.
    /// </summary>
    public static void Sort(long[] array)
    {
        ArgumentNullException.ThrowIfNull(array);
        Sort(array.AsSpan());
    }

    /// <summary>
    /// Sorts a span of long using a sorting network when possible,
    /// with a custom comparer.
    /// </summary>
    public static void Sort(Span<long> span, IComparer<long>? comparer)
    {
        comparer ??= Comparer<long>.Default;
        int n = span.Length;
        if (n == 27 || n == 28)
        {
            ApplyNetworkWithComparer(span, NetworkData.GetNetwork(n), comparer);
            return;
        }

        span.Sort(comparer);
    }

    /// <summary>
    /// Sorts an array of long using a sorting network when possible,
    /// with a custom comparer.
    /// </summary>
    public static void Sort(long[] array, IComparer<long>? comparer)
    {
        ArgumentNullException.ThrowIfNull(array);
        Sort(array.AsSpan(), comparer);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void ApplyNetworkWithComparer(Span<long> span, int[] network, IComparer<long> comparer)
    {
        ref long first = ref MemoryMarshal.GetReference(span);
        for (int i = 0; i < network.Length; i += 2)
        {
            ref long a = ref Unsafe.Add(ref first, network[i]);
            ref long b = ref Unsafe.Add(ref first, network[i + 1]);
            if (comparer.Compare(a, b) > 0)
            {
                long temp = a;
                a = b;
                b = temp;
            }
        }
    }

    /// <summary>
    /// Sorts a span of ulong using a sorting network when possible.
    /// </summary>
    public static void Sort(Span<ulong> span)
    {
        int n = span.Length;
        if (n == 27 || n == 28)
        {
            if (Avx512F.IsSupported)
            {
                if (n == 27)
                    SortSimd27_ulong(span);
                else
                    SortSimd28_ulong(span);
                return;
            }

            ref ulong first = ref MemoryMarshal.GetReference(span);
            if (n == 27)
                Sort27(ref first);
            else
                Sort28(ref first);
            return;
        }

        span.Sort();
    }

    /// <summary>
    /// Sorts an array of ulong using a sorting network when possible.
    /// </summary>
    public static void Sort(ulong[] array)
    {
        ArgumentNullException.ThrowIfNull(array);
        Sort(array.AsSpan());
    }

    /// <summary>
    /// Sorts a span of ulong using a sorting network when possible,
    /// with a custom comparer.
    /// </summary>
    public static void Sort(Span<ulong> span, IComparer<ulong>? comparer)
    {
        comparer ??= Comparer<ulong>.Default;
        int n = span.Length;
        if (n == 27 || n == 28)
        {
            ApplyNetworkWithComparer(span, NetworkData.GetNetwork(n), comparer);
            return;
        }

        span.Sort(comparer);
    }

    /// <summary>
    /// Sorts an array of ulong using a sorting network when possible,
    /// with a custom comparer.
    /// </summary>
    public static void Sort(ulong[] array, IComparer<ulong>? comparer)
    {
        ArgumentNullException.ThrowIfNull(array);
        Sort(array.AsSpan(), comparer);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void ApplyNetworkWithComparer(Span<ulong> span, int[] network, IComparer<ulong> comparer)
    {
        ref ulong first = ref MemoryMarshal.GetReference(span);
        for (int i = 0; i < network.Length; i += 2)
        {
            ref ulong a = ref Unsafe.Add(ref first, network[i]);
            ref ulong b = ref Unsafe.Add(ref first, network[i + 1]);
            if (comparer.Compare(a, b) > 0)
            {
                ulong temp = a;
                a = b;
                b = temp;
            }
        }
    }

    /// <summary>
    /// Sorts a span of nint using a sorting network when possible.
    /// </summary>
    public static void Sort(Span<nint> span)
    {
        int n = span.Length;
        if (nint.Size == 8)
        {
            Sort(MemoryMarshal.Cast<nint, long>(span));
            return;
        }
        if (nint.Size == 4)
        {
            Sort(MemoryMarshal.Cast<nint, int>(span));
            return;
        }
        if (n == 27 || n == 28)
        {
            ref nint first = ref MemoryMarshal.GetReference(span);
            if (n == 27)
                Sort27(ref first);
            else
                Sort28(ref first);
            return;
        }

        span.Sort();
    }

    /// <summary>
    /// Sorts an array of nint using a sorting network when possible.
    /// </summary>
    public static void Sort(nint[] array)
    {
        ArgumentNullException.ThrowIfNull(array);
        Sort(array.AsSpan());
    }

    /// <summary>
    /// Sorts a span of nint using a sorting network when possible,
    /// with a custom comparer.
    /// </summary>
    public static void Sort(Span<nint> span, IComparer<nint>? comparer)
    {
        comparer ??= Comparer<nint>.Default;
        int n = span.Length;
        if (n == 27 || n == 28)
        {
            ApplyNetworkWithComparer(span, NetworkData.GetNetwork(n), comparer);
            return;
        }

        span.Sort(comparer);
    }

    /// <summary>
    /// Sorts an array of nint using a sorting network when possible,
    /// with a custom comparer.
    /// </summary>
    public static void Sort(nint[] array, IComparer<nint>? comparer)
    {
        ArgumentNullException.ThrowIfNull(array);
        Sort(array.AsSpan(), comparer);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void ApplyNetworkWithComparer(Span<nint> span, int[] network, IComparer<nint> comparer)
    {
        ref nint first = ref MemoryMarshal.GetReference(span);
        for (int i = 0; i < network.Length; i += 2)
        {
            ref nint a = ref Unsafe.Add(ref first, network[i]);
            ref nint b = ref Unsafe.Add(ref first, network[i + 1]);
            if (comparer.Compare(a, b) > 0)
            {
                nint temp = a;
                a = b;
                b = temp;
            }
        }
    }

    /// <summary>
    /// Sorts a span of nuint using a sorting network when possible.
    /// </summary>
    public static void Sort(Span<nuint> span)
    {
        int n = span.Length;
        if (nuint.Size == 8)
        {
            Sort(MemoryMarshal.Cast<nuint, ulong>(span));
            return;
        }
        if (nuint.Size == 4)
        {
            Sort(MemoryMarshal.Cast<nuint, uint>(span));
            return;
        }
        if (n == 27 || n == 28)
        {
            ref nuint first = ref MemoryMarshal.GetReference(span);
            if (n == 27)
                Sort27(ref first);
            else
                Sort28(ref first);
            return;
        }

        span.Sort();
    }

    /// <summary>
    /// Sorts an array of nuint using a sorting network when possible.
    /// </summary>
    public static void Sort(nuint[] array)
    {
        ArgumentNullException.ThrowIfNull(array);
        Sort(array.AsSpan());
    }

    /// <summary>
    /// Sorts a span of nuint using a sorting network when possible,
    /// with a custom comparer.
    /// </summary>
    public static void Sort(Span<nuint> span, IComparer<nuint>? comparer)
    {
        comparer ??= Comparer<nuint>.Default;
        int n = span.Length;
        if (n == 27 || n == 28)
        {
            ApplyNetworkWithComparer(span, NetworkData.GetNetwork(n), comparer);
            return;
        }

        span.Sort(comparer);
    }

    /// <summary>
    /// Sorts an array of nuint using a sorting network when possible,
    /// with a custom comparer.
    /// </summary>
    public static void Sort(nuint[] array, IComparer<nuint>? comparer)
    {
        ArgumentNullException.ThrowIfNull(array);
        Sort(array.AsSpan(), comparer);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void ApplyNetworkWithComparer(Span<nuint> span, int[] network, IComparer<nuint> comparer)
    {
        ref nuint first = ref MemoryMarshal.GetReference(span);
        for (int i = 0; i < network.Length; i += 2)
        {
            ref nuint a = ref Unsafe.Add(ref first, network[i]);
            ref nuint b = ref Unsafe.Add(ref first, network[i + 1]);
            if (comparer.Compare(a, b) > 0)
            {
                nuint temp = a;
                a = b;
                b = temp;
            }
        }
    }

    /// <summary>
    /// Sorts a span of char using a sorting network when possible.
    /// </summary>
    public static void Sort(Span<char> span)
    {
        int n = span.Length;
        if (n == 27 || n == 28)
        {
            if (Avx512BW.IsSupported)
            {
                if (n == 27)
                    SortSimd27_char(span);
                else
                    SortSimd28_char(span);
                return;
            }

            if (AdvSimd.Arm64.IsSupported)
            {
                if (n == 27)
                    SortSimdArm27_char(span);
                else
                    SortSimdArm28_char(span);
                return;
            }

            ref char first = ref MemoryMarshal.GetReference(span);
            if (n == 27)
                Sort27(ref first);
            else
                Sort28(ref first);
            return;
        }

        span.Sort();
    }

    /// <summary>
    /// Sorts an array of char using a sorting network when possible.
    /// </summary>
    public static void Sort(char[] array)
    {
        ArgumentNullException.ThrowIfNull(array);
        Sort(array.AsSpan());
    }

    /// <summary>
    /// Sorts a span of char using a sorting network when possible,
    /// with a custom comparer.
    /// </summary>
    public static void Sort(Span<char> span, IComparer<char>? comparer)
    {
        comparer ??= Comparer<char>.Default;
        int n = span.Length;
        if (n == 27 || n == 28)
        {
            ApplyNetworkWithComparer(span, NetworkData.GetNetwork(n), comparer);
            return;
        }

        span.Sort(comparer);
    }

    /// <summary>
    /// Sorts an array of char using a sorting network when possible,
    /// with a custom comparer.
    /// </summary>
    public static void Sort(char[] array, IComparer<char>? comparer)
    {
        ArgumentNullException.ThrowIfNull(array);
        Sort(array.AsSpan(), comparer);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void ApplyNetworkWithComparer(Span<char> span, int[] network, IComparer<char> comparer)
    {
        ref char first = ref MemoryMarshal.GetReference(span);
        for (int i = 0; i < network.Length; i += 2)
        {
            ref char a = ref Unsafe.Add(ref first, network[i]);
            ref char b = ref Unsafe.Add(ref first, network[i + 1]);
            if (comparer.Compare(a, b) > 0)
            {
                char temp = a;
                a = b;
                b = temp;
            }
        }
    }

    /// <summary>
    /// Sorts a span of float using a sorting network when possible.
    /// </summary>
    public static void Sort(Span<float> span)
    {
        int n = span.Length;
        if (n == 27 || n == 28)
        {
            if (Avx512F.IsSupported)
            {
                if (n == 27)
                    SortSimd27_512_float(span);
                else
                    SortSimd28_512_float(span);
                return;
            }

            if (Avx2.IsSupported)
            {
                if (n == 27)
                    SortSimd27_float(span);
                else
                    SortSimd28_float(span);
                return;
            }

            if (AdvSimd.Arm64.IsSupported)
            {
                if (n == 27)
                    SortSimdArm27_float(span);
                else
                    SortSimdArm28_float(span);
                return;
            }

            ref float first = ref MemoryMarshal.GetReference(span);
            if (n == 27)
                Sort27(ref first);
            else
                Sort28(ref first);
            return;
        }

        span.Sort();
    }

    /// <summary>
    /// Sorts an array of float using a sorting network when possible.
    /// </summary>
    public static void Sort(float[] array)
    {
        ArgumentNullException.ThrowIfNull(array);
        Sort(array.AsSpan());
    }

    /// <summary>
    /// Sorts a span of float using a sorting network when possible,
    /// with a custom comparer.
    /// </summary>
    public static void Sort(Span<float> span, IComparer<float>? comparer)
    {
        comparer ??= Comparer<float>.Default;
        int n = span.Length;
        if (n == 27 || n == 28)
        {
            ApplyNetworkWithComparer(span, NetworkData.GetNetwork(n), comparer);
            return;
        }

        span.Sort(comparer);
    }

    /// <summary>
    /// Sorts an array of float using a sorting network when possible,
    /// with a custom comparer.
    /// </summary>
    public static void Sort(float[] array, IComparer<float>? comparer)
    {
        ArgumentNullException.ThrowIfNull(array);
        Sort(array.AsSpan(), comparer);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void ApplyNetworkWithComparer(Span<float> span, int[] network, IComparer<float> comparer)
    {
        ref float first = ref MemoryMarshal.GetReference(span);
        for (int i = 0; i < network.Length; i += 2)
        {
            ref float a = ref Unsafe.Add(ref first, network[i]);
            ref float b = ref Unsafe.Add(ref first, network[i + 1]);
            if (comparer.Compare(a, b) > 0)
            {
                float temp = a;
                a = b;
                b = temp;
            }
        }
    }

    /// <summary>
    /// Sorts a span of double using a sorting network when possible.
    /// </summary>
    public static void Sort(Span<double> span)
    {
        int n = span.Length;
        if (n == 27 || n == 28)
        {
            if (Avx512F.IsSupported)
            {
                if (n == 27)
                    SortSimd27_double(span);
                else
                    SortSimd28_double(span);
                return;
            }

            if (Avx2.IsSupported)
            {
                if (n == 27)
                    SortSimdAvx2_27_double(span);
                else
                    SortSimdAvx2_28_double(span);
                return;
            }

            ref double first = ref MemoryMarshal.GetReference(span);
            if (n == 27)
                Sort27(ref first);
            else
                Sort28(ref first);
            return;
        }

        span.Sort();
    }

    /// <summary>
    /// Sorts an array of double using a sorting network when possible.
    /// </summary>
    public static void Sort(double[] array)
    {
        ArgumentNullException.ThrowIfNull(array);
        Sort(array.AsSpan());
    }

    /// <summary>
    /// Sorts a span of double using a sorting network when possible,
    /// with a custom comparer.
    /// </summary>
    public static void Sort(Span<double> span, IComparer<double>? comparer)
    {
        comparer ??= Comparer<double>.Default;
        int n = span.Length;
        if (n == 27 || n == 28)
        {
            ApplyNetworkWithComparer(span, NetworkData.GetNetwork(n), comparer);
            return;
        }

        span.Sort(comparer);
    }

    /// <summary>
    /// Sorts an array of double using a sorting network when possible,
    /// with a custom comparer.
    /// </summary>
    public static void Sort(double[] array, IComparer<double>? comparer)
    {
        ArgumentNullException.ThrowIfNull(array);
        Sort(array.AsSpan(), comparer);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void ApplyNetworkWithComparer(Span<double> span, int[] network, IComparer<double> comparer)
    {
        ref double first = ref MemoryMarshal.GetReference(span);
        for (int i = 0; i < network.Length; i += 2)
        {
            ref double a = ref Unsafe.Add(ref first, network[i]);
            ref double b = ref Unsafe.Add(ref first, network[i + 1]);
            if (comparer.Compare(a, b) > 0)
            {
                double temp = a;
                a = b;
                b = temp;
            }
        }
    }

    /// <summary>
    /// Sorts a span of string using a sorting network when possible.
    /// Uses ordinal comparison for maximum performance.
    /// </summary>
    public static void Sort(Span<string> span)
    {
        int n = span.Length;
        if (n == 27 || n == 28)
        {
            ref string first = ref MemoryMarshal.GetReference(span);
            if (n == 27)
                Sort27(ref first);
            else
                Sort28(ref first);
            return;
        }

        span.Sort(StringComparer.Ordinal);
    }

    /// <summary>
    /// Sorts an array of string using a sorting network when possible.
    /// Uses ordinal comparison for maximum performance.
    /// </summary>
    public static void Sort(string[] array)
    {
        ArgumentNullException.ThrowIfNull(array);
        Sort(array.AsSpan());
    }

    /// <summary>
    /// Sorts a span of string using a sorting network when possible,
    /// with a custom comparer.
    /// </summary>
    public static void Sort(Span<string> span, IComparer<string>? comparer)
    {
        comparer ??= Comparer<string>.Default;
        int n = span.Length;
        if (n == 27 || n == 28)
        {
            ApplyNetworkWithComparer(span, NetworkData.GetNetwork(n), comparer);
            return;
        }

        span.Sort(comparer);
    }

    /// <summary>
    /// Sorts an array of string using a sorting network when possible,
    /// with a custom comparer.
    /// </summary>
    public static void Sort(string[] array, IComparer<string>? comparer)
    {
        ArgumentNullException.ThrowIfNull(array);
        Sort(array.AsSpan(), comparer);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void ApplyNetworkWithComparer(Span<string> span, int[] network, IComparer<string> comparer)
    {
        ref string first = ref MemoryMarshal.GetReference(span);
        for (int i = 0; i < network.Length; i += 2)
        {
            ref string a = ref Unsafe.Add(ref first, network[i]);
            ref string b = ref Unsafe.Add(ref first, network[i + 1]);
            if (comparer.Compare(a, b) > 0)
            {
                string temp = a;
                a = b;
                b = temp;
            }
        }
    }

    /// <summary>
    /// Sorts an array of <typeparamref name="T"/> using a sorting network when possible.
    /// </summary>
    public static void Sort<T>(T[] array, IComparer<T> comparer)
    {
        ArgumentNullException.ThrowIfNull(array);
        ArgumentNullException.ThrowIfNull(comparer);
        int n = array.Length;
        if (n == 27 || n == 28)
        {
            int[] network = NetworkData.GetNetwork(n);
            for (int i = 0; i < network.Length; i += 2)
            {
                int ai = network[i], bi = network[i + 1];
                if (comparer.Compare(array[ai], array[bi]) > 0)
                {
                    T temp = array[ai];
                    array[ai] = array[bi];
                    array[bi] = temp;
                }
            }
            return;
        }

        Array.Sort(array, comparer);
    }
}
