using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace SortingNetworks;

// <auto-generated>
// This file was generated by generate_unrolled.py
// Do not edit manually.
// </auto-generated>

public static partial class NetworkSort
{
    private static void Sort27(ref int first)
    {
        int e0 = first;
        int e1 = Unsafe.Add(ref first, 1);
        int e2 = Unsafe.Add(ref first, 2);
        int e3 = Unsafe.Add(ref first, 3);
        int e4 = Unsafe.Add(ref first, 4);
        int e5 = Unsafe.Add(ref first, 5);
        int e6 = Unsafe.Add(ref first, 6);
        int e7 = Unsafe.Add(ref first, 7);
        int e8 = Unsafe.Add(ref first, 8);
        int e9 = Unsafe.Add(ref first, 9);
        int e10 = Unsafe.Add(ref first, 10);
        int e11 = Unsafe.Add(ref first, 11);
        int e12 = Unsafe.Add(ref first, 12);
        int e13 = Unsafe.Add(ref first, 13);
        int e14 = Unsafe.Add(ref first, 14);
        int e15 = Unsafe.Add(ref first, 15);
        int e16 = Unsafe.Add(ref first, 16);
        int e17 = Unsafe.Add(ref first, 17);
        int e18 = Unsafe.Add(ref first, 18);
        int e19 = Unsafe.Add(ref first, 19);
        int e20 = Unsafe.Add(ref first, 20);
        int e21 = Unsafe.Add(ref first, 21);
        int e22 = Unsafe.Add(ref first, 22);
        int e23 = Unsafe.Add(ref first, 23);
        int e24 = Unsafe.Add(ref first, 24);
        int e25 = Unsafe.Add(ref first, 25);
        int e26 = Unsafe.Add(ref first, 26);

        if (e1 > e26) { int temp = e1; e1 = e26; e26 = temp; }
        if (e2 > e25) { int temp = e2; e2 = e25; e25 = temp; }
        if (e3 > e24) { int temp = e3; e3 = e24; e24 = temp; }
        if (e4 > e23) { int temp = e4; e4 = e23; e23 = temp; }
        if (e5 > e22) { int temp = e5; e5 = e22; e22 = temp; }
        if (e6 > e21) { int temp = e6; e6 = e21; e21 = temp; }
        if (e7 > e20) { int temp = e7; e7 = e20; e20 = temp; }
        if (e8 > e9) { int temp = e8; e8 = e9; e9 = temp; }
        if (e10 > e11) { int temp = e10; e10 = e11; e11 = temp; }
        if (e12 > e15) { int temp = e12; e12 = e15; e15 = temp; }
        if (e13 > e14) { int temp = e13; e13 = e14; e14 = temp; }
        if (e16 > e17) { int temp = e16; e16 = e17; e17 = temp; }
        if (e18 > e19) { int temp = e18; e18 = e19; e19 = temp; }
        if (e0 > e1) { int temp = e0; e0 = e1; e1 = temp; }
        if (e2 > e3) { int temp = e2; e2 = e3; e3 = temp; }
        if (e4 > e5) { int temp = e4; e4 = e5; e5 = temp; }
        if (e6 > e7) { int temp = e6; e6 = e7; e7 = temp; }
        if (e8 > e10) { int temp = e8; e8 = e10; e10 = temp; }
        if (e9 > e11) { int temp = e9; e9 = e11; e11 = temp; }
        if (e12 > e14) { int temp = e12; e12 = e14; e14 = temp; }
        if (e13 > e15) { int temp = e13; e13 = e15; e15 = temp; }
        if (e16 > e18) { int temp = e16; e16 = e18; e18 = temp; }
        if (e17 > e19) { int temp = e17; e17 = e19; e19 = temp; }
        if (e20 > e21) { int temp = e20; e20 = e21; e21 = temp; }
        if (e22 > e23) { int temp = e22; e22 = e23; e23 = temp; }
        if (e24 > e25) { int temp = e24; e24 = e25; e25 = temp; }
        if (e0 > e2) { int temp = e0; e0 = e2; e2 = temp; }
        if (e1 > e3) { int temp = e1; e1 = e3; e3 = temp; }
        if (e4 > e6) { int temp = e4; e4 = e6; e6 = temp; }
        if (e5 > e7) { int temp = e5; e5 = e7; e7 = temp; }
        if (e8 > e19) { int temp = e8; e8 = e19; e19 = temp; }
        if (e9 > e12) { int temp = e9; e9 = e12; e12 = temp; }
        if (e10 > e14) { int temp = e10; e10 = e14; e14 = temp; }
        if (e11 > e16) { int temp = e11; e11 = e16; e16 = temp; }
        if (e13 > e17) { int temp = e13; e13 = e17; e17 = temp; }
        if (e15 > e18) { int temp = e15; e15 = e18; e18 = temp; }
        if (e20 > e22) { int temp = e20; e20 = e22; e22 = temp; }
        if (e21 > e23) { int temp = e21; e21 = e23; e23 = temp; }
        if (e24 > e26) { int temp = e24; e24 = e26; e26 = temp; }
        if (e0 > e4) { int temp = e0; e0 = e4; e4 = temp; }
        if (e1 > e5) { int temp = e1; e1 = e5; e5 = temp; }
        if (e2 > e20) { int temp = e2; e2 = e20; e20 = temp; }
        if (e3 > e21) { int temp = e3; e3 = e21; e21 = temp; }
        if (e6 > e24) { int temp = e6; e6 = e24; e24 = temp; }
        if (e7 > e25) { int temp = e7; e7 = e25; e25 = temp; }
        if (e8 > e13) { int temp = e8; e8 = e13; e13 = temp; }
        if (e9 > e11) { int temp = e9; e9 = e11; e11 = temp; }
        if (e10 > e17) { int temp = e10; e10 = e17; e17 = temp; }
        if (e12 > e15) { int temp = e12; e12 = e15; e15 = temp; }
        if (e14 > e19) { int temp = e14; e14 = e19; e19 = temp; }
        if (e16 > e18) { int temp = e16; e16 = e18; e18 = temp; }
        if (e22 > e26) { int temp = e22; e22 = e26; e26 = temp; }
        if (e1 > e2) { int temp = e1; e1 = e2; e2 = temp; }
        if (e3 > e24) { int temp = e3; e3 = e24; e24 = temp; }
        if (e4 > e6) { int temp = e4; e4 = e6; e6 = temp; }
        if (e5 > e22) { int temp = e5; e5 = e22; e22 = temp; }
        if (e7 > e20) { int temp = e7; e7 = e20; e20 = temp; }
        if (e8 > e9) { int temp = e8; e8 = e9; e9 = temp; }
        if (e10 > e12) { int temp = e10; e10 = e12; e12 = temp; }
        if (e11 > e13) { int temp = e11; e11 = e13; e13 = temp; }
        if (e14 > e16) { int temp = e14; e14 = e16; e16 = temp; }
        if (e15 > e17) { int temp = e15; e15 = e17; e17 = temp; }
        if (e18 > e19) { int temp = e18; e18 = e19; e19 = temp; }
        if (e21 > e23) { int temp = e21; e21 = e23; e23 = temp; }
        if (e25 > e26) { int temp = e25; e25 = e26; e26 = temp; }
        if (e0 > e8) { int temp = e0; e0 = e8; e8 = temp; }
        if (e1 > e4) { int temp = e1; e1 = e4; e4 = temp; }
        if (e2 > e6) { int temp = e2; e2 = e6; e6 = temp; }
        if (e3 > e9) { int temp = e3; e3 = e9; e9 = temp; }
        if (e5 > e7) { int temp = e5; e5 = e7; e7 = temp; }
        if (e10 > e11) { int temp = e10; e10 = e11; e11 = temp; }
        if (e12 > e13) { int temp = e12; e12 = e13; e13 = temp; }
        if (e14 > e15) { int temp = e14; e14 = e15; e15 = temp; }
        if (e16 > e17) { int temp = e16; e16 = e17; e17 = temp; }
        if (e18 > e24) { int temp = e18; e18 = e24; e24 = temp; }
        if (e20 > e22) { int temp = e20; e20 = e22; e22 = temp; }
        if (e21 > e25) { int temp = e21; e21 = e25; e25 = temp; }
        if (e23 > e26) { int temp = e23; e23 = e26; e26 = temp; }
        if (e1 > e10) { int temp = e1; e1 = e10; e10 = temp; }
        if (e2 > e13) { int temp = e2; e2 = e13; e13 = temp; }
        if (e4 > e8) { int temp = e4; e4 = e8; e8 = temp; }
        if (e5 > e12) { int temp = e5; e5 = e12; e12 = temp; }
        if (e6 > e9) { int temp = e6; e6 = e9; e9 = temp; }
        if (e7 > e20) { int temp = e7; e7 = e20; e20 = temp; }
        if (e14 > e25) { int temp = e14; e14 = e25; e25 = temp; }
        if (e15 > e22) { int temp = e15; e15 = e22; e22 = temp; }
        if (e17 > e26) { int temp = e17; e17 = e26; e26 = temp; }
        if (e18 > e21) { int temp = e18; e18 = e21; e21 = temp; }
        if (e19 > e23) { int temp = e19; e19 = e23; e23 = temp; }
        if (e3 > e4) { int temp = e3; e3 = e4; e4 = temp; }
        if (e6 > e14) { int temp = e6; e6 = e14; e14 = temp; }
        if (e7 > e11) { int temp = e7; e7 = e11; e11 = temp; }
        if (e8 > e15) { int temp = e8; e8 = e15; e15 = temp; }
        if (e9 > e17) { int temp = e9; e9 = e17; e17 = temp; }
        if (e10 > e18) { int temp = e10; e10 = e18; e18 = temp; }
        if (e12 > e19) { int temp = e12; e12 = e19; e19 = temp; }
        if (e13 > e21) { int temp = e13; e13 = e21; e21 = temp; }
        if (e16 > e20) { int temp = e16; e16 = e20; e20 = temp; }
        if (e23 > e24) { int temp = e23; e23 = e24; e24 = temp; }
        if (e2 > e4) { int temp = e2; e2 = e4; e4 = temp; }
        if (e5 > e6) { int temp = e5; e5 = e6; e6 = temp; }
        if (e7 > e8) { int temp = e7; e7 = e8; e8 = temp; }
        if (e9 > e13) { int temp = e9; e9 = e13; e13 = temp; }
        if (e11 > e15) { int temp = e11; e11 = e15; e15 = temp; }
        if (e12 > e16) { int temp = e12; e12 = e16; e16 = temp; }
        if (e14 > e18) { int temp = e14; e14 = e18; e18 = temp; }
        if (e19 > e20) { int temp = e19; e19 = e20; e20 = temp; }
        if (e21 > e22) { int temp = e21; e21 = e22; e22 = temp; }
        if (e23 > e25) { int temp = e23; e23 = e25; e25 = temp; }
        if (e2 > e7) { int temp = e2; e2 = e7; e7 = temp; }
        if (e4 > e8) { int temp = e4; e4 = e8; e8 = temp; }
        if (e6 > e10) { int temp = e6; e6 = e10; e10 = temp; }
        if (e9 > e11) { int temp = e9; e9 = e11; e11 = temp; }
        if (e12 > e14) { int temp = e12; e12 = e14; e14 = temp; }
        if (e13 > e15) { int temp = e13; e13 = e15; e15 = temp; }
        if (e16 > e18) { int temp = e16; e16 = e18; e18 = temp; }
        if (e17 > e21) { int temp = e17; e17 = e21; e21 = temp; }
        if (e19 > e23) { int temp = e19; e19 = e23; e23 = temp; }
        if (e20 > e25) { int temp = e20; e20 = e25; e25 = temp; }
        if (e1 > e3) { int temp = e1; e1 = e3; e3 = temp; }
        if (e4 > e7) { int temp = e4; e4 = e7; e7 = temp; }
        if (e5 > e6) { int temp = e5; e5 = e6; e6 = temp; }
        if (e8 > e9) { int temp = e8; e8 = e9; e9 = temp; }
        if (e10 > e12) { int temp = e10; e10 = e12; e12 = temp; }
        if (e11 > e16) { int temp = e11; e11 = e16; e16 = temp; }
        if (e13 > e14) { int temp = e13; e13 = e14; e14 = temp; }
        if (e15 > e17) { int temp = e15; e15 = e17; e17 = temp; }
        if (e18 > e19) { int temp = e18; e18 = e19; e19 = temp; }
        if (e20 > e23) { int temp = e20; e20 = e23; e23 = temp; }
        if (e21 > e22) { int temp = e21; e21 = e22; e22 = temp; }
        if (e24 > e26) { int temp = e24; e24 = e26; e26 = temp; }
        if (e2 > e3) { int temp = e2; e2 = e3; e3 = temp; }
        if (e4 > e5) { int temp = e4; e4 = e5; e5 = temp; }
        if (e6 > e7) { int temp = e6; e6 = e7; e7 = temp; }
        if (e8 > e10) { int temp = e8; e8 = e10; e10 = temp; }
        if (e9 > e12) { int temp = e9; e9 = e12; e12 = temp; }
        if (e11 > e13) { int temp = e11; e11 = e13; e13 = temp; }
        if (e14 > e16) { int temp = e14; e14 = e16; e16 = temp; }
        if (e15 > e18) { int temp = e15; e15 = e18; e18 = temp; }
        if (e17 > e19) { int temp = e17; e17 = e19; e19 = temp; }
        if (e20 > e21) { int temp = e20; e20 = e21; e21 = temp; }
        if (e22 > e23) { int temp = e22; e22 = e23; e23 = temp; }
        if (e24 > e25) { int temp = e24; e24 = e25; e25 = temp; }
        if (e3 > e4) { int temp = e3; e3 = e4; e4 = temp; }
        if (e5 > e6) { int temp = e5; e5 = e6; e6 = temp; }
        if (e7 > e8) { int temp = e7; e7 = e8; e8 = temp; }
        if (e9 > e10) { int temp = e9; e9 = e10; e10 = temp; }
        if (e11 > e12) { int temp = e11; e11 = e12; e12 = temp; }
        if (e13 > e14) { int temp = e13; e13 = e14; e14 = temp; }
        if (e15 > e16) { int temp = e15; e15 = e16; e16 = temp; }
        if (e17 > e18) { int temp = e17; e17 = e18; e18 = temp; }
        if (e19 > e20) { int temp = e19; e19 = e20; e20 = temp; }
        if (e21 > e22) { int temp = e21; e21 = e22; e22 = temp; }
        if (e23 > e24) { int temp = e23; e23 = e24; e24 = temp; }

        first = e0;
        Unsafe.Add(ref first, 1) = e1;
        Unsafe.Add(ref first, 2) = e2;
        Unsafe.Add(ref first, 3) = e3;
        Unsafe.Add(ref first, 4) = e4;
        Unsafe.Add(ref first, 5) = e5;
        Unsafe.Add(ref first, 6) = e6;
        Unsafe.Add(ref first, 7) = e7;
        Unsafe.Add(ref first, 8) = e8;
        Unsafe.Add(ref first, 9) = e9;
        Unsafe.Add(ref first, 10) = e10;
        Unsafe.Add(ref first, 11) = e11;
        Unsafe.Add(ref first, 12) = e12;
        Unsafe.Add(ref first, 13) = e13;
        Unsafe.Add(ref first, 14) = e14;
        Unsafe.Add(ref first, 15) = e15;
        Unsafe.Add(ref first, 16) = e16;
        Unsafe.Add(ref first, 17) = e17;
        Unsafe.Add(ref first, 18) = e18;
        Unsafe.Add(ref first, 19) = e19;
        Unsafe.Add(ref first, 20) = e20;
        Unsafe.Add(ref first, 21) = e21;
        Unsafe.Add(ref first, 22) = e22;
        Unsafe.Add(ref first, 23) = e23;
        Unsafe.Add(ref first, 24) = e24;
        Unsafe.Add(ref first, 25) = e25;
        Unsafe.Add(ref first, 26) = e26;
    }

    private static void Sort28(ref int first)
    {
        int e0 = first;
        int e1 = Unsafe.Add(ref first, 1);
        int e2 = Unsafe.Add(ref first, 2);
        int e3 = Unsafe.Add(ref first, 3);
        int e4 = Unsafe.Add(ref first, 4);
        int e5 = Unsafe.Add(ref first, 5);
        int e6 = Unsafe.Add(ref first, 6);
        int e7 = Unsafe.Add(ref first, 7);
        int e8 = Unsafe.Add(ref first, 8);
        int e9 = Unsafe.Add(ref first, 9);
        int e10 = Unsafe.Add(ref first, 10);
        int e11 = Unsafe.Add(ref first, 11);
        int e12 = Unsafe.Add(ref first, 12);
        int e13 = Unsafe.Add(ref first, 13);
        int e14 = Unsafe.Add(ref first, 14);
        int e15 = Unsafe.Add(ref first, 15);
        int e16 = Unsafe.Add(ref first, 16);
        int e17 = Unsafe.Add(ref first, 17);
        int e18 = Unsafe.Add(ref first, 18);
        int e19 = Unsafe.Add(ref first, 19);
        int e20 = Unsafe.Add(ref first, 20);
        int e21 = Unsafe.Add(ref first, 21);
        int e22 = Unsafe.Add(ref first, 22);
        int e23 = Unsafe.Add(ref first, 23);
        int e24 = Unsafe.Add(ref first, 24);
        int e25 = Unsafe.Add(ref first, 25);
        int e26 = Unsafe.Add(ref first, 26);
        int e27 = Unsafe.Add(ref first, 27);

        if (e0 > e27) { int temp = e0; e0 = e27; e27 = temp; }
        if (e1 > e26) { int temp = e1; e1 = e26; e26 = temp; }
        if (e2 > e25) { int temp = e2; e2 = e25; e25 = temp; }
        if (e3 > e24) { int temp = e3; e3 = e24; e24 = temp; }
        if (e4 > e23) { int temp = e4; e4 = e23; e23 = temp; }
        if (e5 > e22) { int temp = e5; e5 = e22; e22 = temp; }
        if (e6 > e21) { int temp = e6; e6 = e21; e21 = temp; }
        if (e7 > e20) { int temp = e7; e7 = e20; e20 = temp; }
        if (e8 > e9) { int temp = e8; e8 = e9; e9 = temp; }
        if (e10 > e11) { int temp = e10; e10 = e11; e11 = temp; }
        if (e12 > e15) { int temp = e12; e12 = e15; e15 = temp; }
        if (e13 > e14) { int temp = e13; e13 = e14; e14 = temp; }
        if (e16 > e17) { int temp = e16; e16 = e17; e17 = temp; }
        if (e18 > e19) { int temp = e18; e18 = e19; e19 = temp; }
        if (e0 > e1) { int temp = e0; e0 = e1; e1 = temp; }
        if (e2 > e3) { int temp = e2; e2 = e3; e3 = temp; }
        if (e4 > e5) { int temp = e4; e4 = e5; e5 = temp; }
        if (e6 > e7) { int temp = e6; e6 = e7; e7 = temp; }
        if (e8 > e10) { int temp = e8; e8 = e10; e10 = temp; }
        if (e9 > e11) { int temp = e9; e9 = e11; e11 = temp; }
        if (e12 > e14) { int temp = e12; e12 = e14; e14 = temp; }
        if (e13 > e15) { int temp = e13; e13 = e15; e15 = temp; }
        if (e16 > e18) { int temp = e16; e16 = e18; e18 = temp; }
        if (e17 > e19) { int temp = e17; e17 = e19; e19 = temp; }
        if (e20 > e21) { int temp = e20; e20 = e21; e21 = temp; }
        if (e22 > e23) { int temp = e22; e22 = e23; e23 = temp; }
        if (e24 > e25) { int temp = e24; e24 = e25; e25 = temp; }
        if (e26 > e27) { int temp = e26; e26 = e27; e27 = temp; }
        if (e0 > e2) { int temp = e0; e0 = e2; e2 = temp; }
        if (e1 > e3) { int temp = e1; e1 = e3; e3 = temp; }
        if (e4 > e6) { int temp = e4; e4 = e6; e6 = temp; }
        if (e5 > e7) { int temp = e5; e5 = e7; e7 = temp; }
        if (e8 > e19) { int temp = e8; e8 = e19; e19 = temp; }
        if (e9 > e12) { int temp = e9; e9 = e12; e12 = temp; }
        if (e10 > e14) { int temp = e10; e10 = e14; e14 = temp; }
        if (e11 > e16) { int temp = e11; e11 = e16; e16 = temp; }
        if (e13 > e17) { int temp = e13; e13 = e17; e17 = temp; }
        if (e15 > e18) { int temp = e15; e15 = e18; e18 = temp; }
        if (e20 > e22) { int temp = e20; e20 = e22; e22 = temp; }
        if (e21 > e23) { int temp = e21; e21 = e23; e23 = temp; }
        if (e24 > e26) { int temp = e24; e24 = e26; e26 = temp; }
        if (e25 > e27) { int temp = e25; e25 = e27; e27 = temp; }
        if (e0 > e4) { int temp = e0; e0 = e4; e4 = temp; }
        if (e1 > e5) { int temp = e1; e1 = e5; e5 = temp; }
        if (e2 > e20) { int temp = e2; e2 = e20; e20 = temp; }
        if (e3 > e21) { int temp = e3; e3 = e21; e21 = temp; }
        if (e6 > e24) { int temp = e6; e6 = e24; e24 = temp; }
        if (e7 > e25) { int temp = e7; e7 = e25; e25 = temp; }
        if (e8 > e13) { int temp = e8; e8 = e13; e13 = temp; }
        if (e9 > e11) { int temp = e9; e9 = e11; e11 = temp; }
        if (e10 > e17) { int temp = e10; e10 = e17; e17 = temp; }
        if (e12 > e15) { int temp = e12; e12 = e15; e15 = temp; }
        if (e14 > e19) { int temp = e14; e14 = e19; e19 = temp; }
        if (e16 > e18) { int temp = e16; e16 = e18; e18 = temp; }
        if (e22 > e26) { int temp = e22; e22 = e26; e26 = temp; }
        if (e23 > e27) { int temp = e23; e23 = e27; e27 = temp; }
        if (e1 > e2) { int temp = e1; e1 = e2; e2 = temp; }
        if (e3 > e24) { int temp = e3; e3 = e24; e24 = temp; }
        if (e4 > e6) { int temp = e4; e4 = e6; e6 = temp; }
        if (e5 > e22) { int temp = e5; e5 = e22; e22 = temp; }
        if (e7 > e20) { int temp = e7; e7 = e20; e20 = temp; }
        if (e8 > e9) { int temp = e8; e8 = e9; e9 = temp; }
        if (e10 > e12) { int temp = e10; e10 = e12; e12 = temp; }
        if (e11 > e13) { int temp = e11; e11 = e13; e13 = temp; }
        if (e14 > e16) { int temp = e14; e14 = e16; e16 = temp; }
        if (e15 > e17) { int temp = e15; e15 = e17; e17 = temp; }
        if (e18 > e19) { int temp = e18; e18 = e19; e19 = temp; }
        if (e21 > e23) { int temp = e21; e21 = e23; e23 = temp; }
        if (e25 > e26) { int temp = e25; e25 = e26; e26 = temp; }
        if (e0 > e8) { int temp = e0; e0 = e8; e8 = temp; }
        if (e1 > e4) { int temp = e1; e1 = e4; e4 = temp; }
        if (e2 > e6) { int temp = e2; e2 = e6; e6 = temp; }
        if (e3 > e9) { int temp = e3; e3 = e9; e9 = temp; }
        if (e5 > e7) { int temp = e5; e5 = e7; e7 = temp; }
        if (e10 > e11) { int temp = e10; e10 = e11; e11 = temp; }
        if (e12 > e13) { int temp = e12; e12 = e13; e13 = temp; }
        if (e14 > e15) { int temp = e14; e14 = e15; e15 = temp; }
        if (e16 > e17) { int temp = e16; e16 = e17; e17 = temp; }
        if (e18 > e24) { int temp = e18; e18 = e24; e24 = temp; }
        if (e19 > e27) { int temp = e19; e19 = e27; e27 = temp; }
        if (e20 > e22) { int temp = e20; e20 = e22; e22 = temp; }
        if (e21 > e25) { int temp = e21; e21 = e25; e25 = temp; }
        if (e23 > e26) { int temp = e23; e23 = e26; e26 = temp; }
        if (e1 > e10) { int temp = e1; e1 = e10; e10 = temp; }
        if (e2 > e13) { int temp = e2; e2 = e13; e13 = temp; }
        if (e4 > e8) { int temp = e4; e4 = e8; e8 = temp; }
        if (e5 > e12) { int temp = e5; e5 = e12; e12 = temp; }
        if (e6 > e9) { int temp = e6; e6 = e9; e9 = temp; }
        if (e7 > e20) { int temp = e7; e7 = e20; e20 = temp; }
        if (e14 > e25) { int temp = e14; e14 = e25; e25 = temp; }
        if (e15 > e22) { int temp = e15; e15 = e22; e22 = temp; }
        if (e17 > e26) { int temp = e17; e17 = e26; e26 = temp; }
        if (e18 > e21) { int temp = e18; e18 = e21; e21 = temp; }
        if (e19 > e23) { int temp = e19; e19 = e23; e23 = temp; }
        if (e3 > e4) { int temp = e3; e3 = e4; e4 = temp; }
        if (e6 > e14) { int temp = e6; e6 = e14; e14 = temp; }
        if (e7 > e11) { int temp = e7; e7 = e11; e11 = temp; }
        if (e8 > e15) { int temp = e8; e8 = e15; e15 = temp; }
        if (e9 > e17) { int temp = e9; e9 = e17; e17 = temp; }
        if (e10 > e18) { int temp = e10; e10 = e18; e18 = temp; }
        if (e12 > e19) { int temp = e12; e12 = e19; e19 = temp; }
        if (e13 > e21) { int temp = e13; e13 = e21; e21 = temp; }
        if (e16 > e20) { int temp = e16; e16 = e20; e20 = temp; }
        if (e23 > e24) { int temp = e23; e23 = e24; e24 = temp; }
        if (e2 > e4) { int temp = e2; e2 = e4; e4 = temp; }
        if (e5 > e6) { int temp = e5; e5 = e6; e6 = temp; }
        if (e7 > e8) { int temp = e7; e7 = e8; e8 = temp; }
        if (e9 > e13) { int temp = e9; e9 = e13; e13 = temp; }
        if (e11 > e15) { int temp = e11; e11 = e15; e15 = temp; }
        if (e12 > e16) { int temp = e12; e12 = e16; e16 = temp; }
        if (e14 > e18) { int temp = e14; e14 = e18; e18 = temp; }
        if (e19 > e20) { int temp = e19; e19 = e20; e20 = temp; }
        if (e21 > e22) { int temp = e21; e21 = e22; e22 = temp; }
        if (e23 > e25) { int temp = e23; e23 = e25; e25 = temp; }
        if (e2 > e7) { int temp = e2; e2 = e7; e7 = temp; }
        if (e4 > e8) { int temp = e4; e4 = e8; e8 = temp; }
        if (e6 > e10) { int temp = e6; e6 = e10; e10 = temp; }
        if (e9 > e11) { int temp = e9; e9 = e11; e11 = temp; }
        if (e12 > e14) { int temp = e12; e12 = e14; e14 = temp; }
        if (e13 > e15) { int temp = e13; e13 = e15; e15 = temp; }
        if (e16 > e18) { int temp = e16; e16 = e18; e18 = temp; }
        if (e17 > e21) { int temp = e17; e17 = e21; e21 = temp; }
        if (e19 > e23) { int temp = e19; e19 = e23; e23 = temp; }
        if (e20 > e25) { int temp = e20; e20 = e25; e25 = temp; }
        if (e1 > e3) { int temp = e1; e1 = e3; e3 = temp; }
        if (e4 > e7) { int temp = e4; e4 = e7; e7 = temp; }
        if (e5 > e6) { int temp = e5; e5 = e6; e6 = temp; }
        if (e8 > e9) { int temp = e8; e8 = e9; e9 = temp; }
        if (e10 > e12) { int temp = e10; e10 = e12; e12 = temp; }
        if (e11 > e16) { int temp = e11; e11 = e16; e16 = temp; }
        if (e13 > e14) { int temp = e13; e13 = e14; e14 = temp; }
        if (e15 > e17) { int temp = e15; e15 = e17; e17 = temp; }
        if (e18 > e19) { int temp = e18; e18 = e19; e19 = temp; }
        if (e20 > e23) { int temp = e20; e20 = e23; e23 = temp; }
        if (e21 > e22) { int temp = e21; e21 = e22; e22 = temp; }
        if (e24 > e26) { int temp = e24; e24 = e26; e26 = temp; }
        if (e2 > e3) { int temp = e2; e2 = e3; e3 = temp; }
        if (e4 > e5) { int temp = e4; e4 = e5; e5 = temp; }
        if (e6 > e7) { int temp = e6; e6 = e7; e7 = temp; }
        if (e8 > e10) { int temp = e8; e8 = e10; e10 = temp; }
        if (e9 > e12) { int temp = e9; e9 = e12; e12 = temp; }
        if (e11 > e13) { int temp = e11; e11 = e13; e13 = temp; }
        if (e14 > e16) { int temp = e14; e14 = e16; e16 = temp; }
        if (e15 > e18) { int temp = e15; e15 = e18; e18 = temp; }
        if (e17 > e19) { int temp = e17; e17 = e19; e19 = temp; }
        if (e20 > e21) { int temp = e20; e20 = e21; e21 = temp; }
        if (e22 > e23) { int temp = e22; e22 = e23; e23 = temp; }
        if (e24 > e25) { int temp = e24; e24 = e25; e25 = temp; }
        if (e3 > e4) { int temp = e3; e3 = e4; e4 = temp; }
        if (e5 > e6) { int temp = e5; e5 = e6; e6 = temp; }
        if (e7 > e8) { int temp = e7; e7 = e8; e8 = temp; }
        if (e9 > e10) { int temp = e9; e9 = e10; e10 = temp; }
        if (e11 > e12) { int temp = e11; e11 = e12; e12 = temp; }
        if (e13 > e14) { int temp = e13; e13 = e14; e14 = temp; }
        if (e15 > e16) { int temp = e15; e15 = e16; e16 = temp; }
        if (e17 > e18) { int temp = e17; e17 = e18; e18 = temp; }
        if (e19 > e20) { int temp = e19; e19 = e20; e20 = temp; }
        if (e21 > e22) { int temp = e21; e21 = e22; e22 = temp; }
        if (e23 > e24) { int temp = e23; e23 = e24; e24 = temp; }

        first = e0;
        Unsafe.Add(ref first, 1) = e1;
        Unsafe.Add(ref first, 2) = e2;
        Unsafe.Add(ref first, 3) = e3;
        Unsafe.Add(ref first, 4) = e4;
        Unsafe.Add(ref first, 5) = e5;
        Unsafe.Add(ref first, 6) = e6;
        Unsafe.Add(ref first, 7) = e7;
        Unsafe.Add(ref first, 8) = e8;
        Unsafe.Add(ref first, 9) = e9;
        Unsafe.Add(ref first, 10) = e10;
        Unsafe.Add(ref first, 11) = e11;
        Unsafe.Add(ref first, 12) = e12;
        Unsafe.Add(ref first, 13) = e13;
        Unsafe.Add(ref first, 14) = e14;
        Unsafe.Add(ref first, 15) = e15;
        Unsafe.Add(ref first, 16) = e16;
        Unsafe.Add(ref first, 17) = e17;
        Unsafe.Add(ref first, 18) = e18;
        Unsafe.Add(ref first, 19) = e19;
        Unsafe.Add(ref first, 20) = e20;
        Unsafe.Add(ref first, 21) = e21;
        Unsafe.Add(ref first, 22) = e22;
        Unsafe.Add(ref first, 23) = e23;
        Unsafe.Add(ref first, 24) = e24;
        Unsafe.Add(ref first, 25) = e25;
        Unsafe.Add(ref first, 26) = e26;
        Unsafe.Add(ref first, 27) = e27;
    }
}
