/// Generate unrolled sorting network methods for SortingNetworks.
/// Usage: dotnet run generate_unrolled.cs

using System.Text;

// Primitive .NET types to specialize (all sortable primitives)
string[] primitiveTypes =
[
    "byte", "sbyte", "short", "ushort",
    "int", "uint", "long", "ulong",
    "nint", "nuint", "char", "float", "double",
];

// --- Network28 from the paper ---
int[] network28Flat =
[
    0,27, 1,26, 2,25, 3,24, 4,23, 5,22, 6,21, 7,20, 8,9, 10,11, 12,15, 13,14, 16,17, 18,19,
    0,1, 2,3, 4,5, 6,7, 8,10, 9,11, 12,14, 13,15, 16,18, 17,19, 20,21, 22,23, 24,25, 26,27,
    0,2, 1,3, 4,6, 5,7, 8,19, 9,12, 10,14, 11,16, 13,17, 15,18, 20,22, 21,23, 24,26, 25,27,
    0,4, 1,5, 2,20, 3,21, 6,24, 7,25, 8,13, 9,11, 10,17, 12,15, 14,19, 16,18, 22,26, 23,27,
    1,2, 3,24, 4,6, 5,22, 7,20, 8,9, 10,12, 11,13, 14,16, 15,17, 18,19, 21,23, 25,26,
    0,8, 1,4, 2,6, 3,9, 5,7, 10,11, 12,13, 14,15, 16,17, 18,24, 19,27, 20,22, 21,25, 23,26,
    1,10, 2,13, 4,8, 5,12, 6,9, 7,20, 14,25, 15,22, 17,26, 18,21, 19,23,
    3,4, 6,14, 7,11, 8,15, 9,17, 10,18, 12,19, 13,21, 16,20, 23,24,
    2,4, 5,6, 7,8, 9,13, 11,15, 12,16, 14,18, 19,20, 21,22, 23,25,
    2,7, 4,8, 6,10, 9,11, 12,14, 13,15, 16,18, 17,21, 19,23, 20,25,
    1,3, 4,7, 5,6, 8,9, 10,12, 11,16, 13,14, 15,17, 18,19, 20,23, 21,22, 24,26,
    2,3, 4,5, 6,7, 8,10, 9,12, 11,13, 14,16, 15,18, 17,19, 20,21, 22,23, 24,25,
    3,4, 5,6, 7,8, 9,10, 11,12, 13,14, 15,16, 17,18, 19,20, 21,22, 23,24,
];

// --- Main ---

string baseDir = args.Length > 0 ? args[0] : "SortingNetworks";

string apiPath = Path.Combine(baseDir, "NetworkSort.cs");
using (var w = new StreamWriter(apiPath, false, new UTF8Encoding(false)))
    WriteApiFile(w);
Console.WriteLine($"Generated {apiPath}");

string unrolledPath = Path.Combine(baseDir, "NetworkSort.Unrolled.cs");
using (var w = new StreamWriter(unrolledPath, false, new UTF8Encoding(false)))
    WriteUnrolledFile(w);
Console.WriteLine($"Generated {unrolledPath}");

// Print stats
for (int n = 27; n <= 28; n++)
{
    var pairs = GetNetwork(n);
    Console.WriteLine($"  Sort{n}: {pairs.Count} compare-swaps");
}
Console.WriteLine($"  Types: {string.Join(", ", primitiveTypes)}");

// --- Batcher's odd-even merge sort network generator ---

void BatcherSort(int lo, int hi, int n, List<(int A, int B)> pairs)
{
    if (lo >= hi) return;
    int mid = lo + (hi - lo) / 2;
    BatcherSort(lo, mid, n, pairs);
    BatcherSort(mid + 1, hi, n, pairs);
    BatcherMerge(lo, hi, 1, n, pairs);
}

void BatcherMerge(int lo, int hi, int step, int n, List<(int A, int B)> pairs)
{
    int doubleStep = step * 2;
    if (doubleStep > hi - lo)
    {
        if (lo < n && lo + step < n)
            pairs.Add((lo, lo + step));
        return;
    }
    BatcherMerge(lo, hi, doubleStep, n, pairs);
    BatcherMerge(lo + step, hi, doubleStep, n, pairs);
    for (int i = lo + step; i + step <= hi; i += doubleStep)
    {
        if (i < n && i + step < n)
            pairs.Add((i, i + step));
    }
}

List<(int A, int B)> GenerateBatcherNetwork(int n)
{
    int p = 1;
    while (p < n) p <<= 1;
    var pairs = new List<(int A, int B)>();
    BatcherSort(0, p - 1, n, pairs);
    return pairs;
}

List<(int A, int B)> GetNetwork28()
{
    var pairs = new List<(int A, int B)>();
    for (int i = 0; i < network28Flat.Length; i += 2)
        pairs.Add((network28Flat[i], network28Flat[i + 1]));
    return pairs;
}

List<(int A, int B)> GetNetwork27()
{
    var pairs = new List<(int A, int B)>();
    foreach (var (a, b) in GetNetwork28())
    {
        if (a < 27 && b < 27)
            pairs.Add((a, b));
    }
    return pairs;
}

List<(int A, int B)> GetNetwork(int n) => n switch
{
    28 => GetNetwork28(),
    27 => GetNetwork27(),
    _ => GenerateBatcherNetwork(n),
};

// --- Code generation ---

void WriteFileHeader(StreamWriter w)
{
    w.Write("""
        using System.Runtime.CompilerServices;
        using System.Runtime.InteropServices;

        namespace SortingNetworks;

        // <auto-generated>
        // This file was generated by generate_unrolled.cs
        // Do not edit manually.
        // </auto-generated>


        """);
}

void WriteUnrolledMethod(StreamWriter w, int n, List<(int A, int B)> pairs, string typeName)
{
    if (n <= 8)
        w.WriteLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
    w.WriteLine($"    private static void Sort{n}(ref {typeName} first)");
    w.WriteLine("    {");
    w.WriteLine($"        {typeName} e0 = first;");
    for (int i = 1; i < n; i++)
        w.WriteLine($"        {typeName} e{i} = Unsafe.Add(ref first, {i});");
    w.WriteLine();
    foreach (var (a, b) in pairs)
    {
        if (typeName == "string")
            w.WriteLine($"        if (string.CompareOrdinal(e{a}, e{b}) > 0) {{ {typeName} temp = e{a}; e{a} = e{b}; e{b} = temp; }}");
        else
            w.WriteLine($"        if (e{a} > e{b}) {{ {typeName} temp = e{a}; e{a} = e{b}; e{b} = temp; }}");
    }
    w.WriteLine();
    w.WriteLine("        first = e0;");
    for (int i = 1; i < n; i++)
        w.WriteLine($"        Unsafe.Add(ref first, {i}) = e{i};");
    w.WriteLine("    }");
}

void WritePublicApi(StreamWriter w, string t)
{
    w.Write($$"""
            /// <summary>
            /// Sorts a span of {{t}} using a sorting network when possible.
            /// </summary>
            public static void Sort(Span<{{t}}> span)
            {
                int n = span.Length;
                if (n == 27 || n == 28)
                {
                    ref {{t}} first = ref MemoryMarshal.GetReference(span);
                    if (n == 27)
                        Sort27(ref first);
                    else
                        Sort28(ref first);
                    return;
                }

                span.Sort();
            }

            /// <summary>
            /// Sorts an array of {{t}} using a sorting network when possible.
            /// </summary>
            public static void Sort({{t}}[] array)
            {
                ArgumentNullException.ThrowIfNull(array);
                Sort(array.AsSpan());
            }

            /// <summary>
            /// Sorts a span of {{t}} using a sorting network when possible,
            /// with a custom comparer.
            /// </summary>
            public static void Sort(Span<{{t}}> span, IComparer<{{t}}>? comparer)
            {
                comparer ??= Comparer<{{t}}>.Default;
                int n = span.Length;
                if (n == 27 || n == 28)
                {
                    ApplyNetworkWithComparer(span, NetworkData.GetNetwork(n), comparer);
                    return;
                }

                span.Sort(comparer);
            }

            /// <summary>
            /// Sorts an array of {{t}} using a sorting network when possible,
            /// with a custom comparer.
            /// </summary>
            public static void Sort({{t}}[] array, IComparer<{{t}}>? comparer)
            {
                ArgumentNullException.ThrowIfNull(array);
                Sort(array.AsSpan(), comparer);
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            private static void ApplyNetworkWithComparer(Span<{{t}}> span, int[] network, IComparer<{{t}}> comparer)
            {
                ref {{t}} first = ref MemoryMarshal.GetReference(span);
                for (int i = 0; i < network.Length; i += 2)
                {
                    ref {{t}} a = ref Unsafe.Add(ref first, network[i]);
                    ref {{t}} b = ref Unsafe.Add(ref first, network[i + 1]);
                    if (comparer.Compare(a, b) > 0)
                    {
                        {{t}} temp = a;
                        a = b;
                        b = temp;
                    }
                }
            }

        """);
}

void WriteStringApi(StreamWriter w)
{
    w.Write("""
            /// <summary>
            /// Sorts a span of string using a sorting network when possible.
            /// Uses ordinal comparison for maximum performance.
            /// </summary>
            public static void Sort(Span<string> span)
            {
                int n = span.Length;
                if (n == 27 || n == 28)
                {
                    ref string first = ref MemoryMarshal.GetReference(span);
                    if (n == 27)
                        Sort27(ref first);
                    else
                        Sort28(ref first);
                    return;
                }

                span.Sort(StringComparer.Ordinal);
            }

            /// <summary>
            /// Sorts an array of string using a sorting network when possible.
            /// Uses ordinal comparison for maximum performance.
            /// </summary>
            public static void Sort(string[] array)
            {
                ArgumentNullException.ThrowIfNull(array);
                Sort(array.AsSpan());
            }

            /// <summary>
            /// Sorts a span of string using a sorting network when possible,
            /// with a custom comparer.
            /// </summary>
            public static void Sort(Span<string> span, IComparer<string>? comparer)
            {
                comparer ??= Comparer<string>.Default;
                int n = span.Length;
                if (n == 27 || n == 28)
                {
                    ApplyNetworkWithComparer(span, NetworkData.GetNetwork(n), comparer);
                    return;
                }

                span.Sort(comparer);
            }

            /// <summary>
            /// Sorts an array of string using a sorting network when possible,
            /// with a custom comparer.
            /// </summary>
            public static void Sort(string[] array, IComparer<string>? comparer)
            {
                ArgumentNullException.ThrowIfNull(array);
                Sort(array.AsSpan(), comparer);
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            private static void ApplyNetworkWithComparer(Span<string> span, int[] network, IComparer<string> comparer)
            {
                ref string first = ref MemoryMarshal.GetReference(span);
                for (int i = 0; i < network.Length; i += 2)
                {
                    ref string a = ref Unsafe.Add(ref first, network[i]);
                    ref string b = ref Unsafe.Add(ref first, network[i + 1]);
                    if (comparer.Compare(a, b) > 0)
                    {
                        string temp = a;
                        a = b;
                        b = temp;
                    }
                }
            }

        """);
}

void WriteGenericSortT(StreamWriter w)
{
    w.Write("""
            /// <summary>
            /// Sorts an array of <typeparamref name="T"/> using a sorting network when possible.
            /// </summary>
            public static void Sort<T>(T[] array, IComparer<T> comparer)
            {
                ArgumentNullException.ThrowIfNull(array);
                ArgumentNullException.ThrowIfNull(comparer);
                int n = array.Length;
                if (n == 27 || n == 28)
                {
                    int[] network = NetworkData.GetNetwork(n);
                    for (int i = 0; i < network.Length; i += 2)
                    {
                        int ai = network[i], bi = network[i + 1];
                        if (comparer.Compare(array[ai], array[bi]) > 0)
                        {
                            T temp = array[ai];
                            array[ai] = array[bi];
                            array[bi] = temp;
                        }
                    }
                    return;
                }

                Array.Sort(array, comparer);
            }

        """);
}

void WriteApiFile(StreamWriter w)
{
    WriteFileHeader(w);
    w.Write("""
        /// <summary>
        /// Provides sorting-network-based sorting for small collections.
        /// Uses fixed compare-and-swap networks for sizes up to 28, including
        /// depth-13 networks for 27 and 28 channels from arXiv:2511.04107.
        /// Falls back to the default .NET sort for larger inputs.
        /// </summary>
        public static partial class NetworkSort
        {

        """);

    for (int i = 0; i < primitiveTypes.Length; i++)
    {
        if (i > 0) w.WriteLine();
        WritePublicApi(w, primitiveTypes[i]);
    }

    w.WriteLine();
    WriteStringApi(w);

    w.WriteLine();
    WriteGenericSortT(w);

    w.WriteLine("}");
}

void WriteUnrolledFile(StreamWriter w)
{
    WriteFileHeader(w);
    w.WriteLine("public static partial class NetworkSort");
    w.WriteLine("{");

    bool firstMethod = true;
    foreach (string typeName in primitiveTypes.Concat(["string"]))
    {
        foreach (int n in new[] { 27, 28 })
        {
            var pairs = GetNetwork(n);
            if (!firstMethod) w.WriteLine();
            WriteUnrolledMethod(w, n, pairs, typeName);
            firstMethod = false;
        }
    }

    w.WriteLine("}");
}
