"""Generate unrolled sorting network methods for SortingNetworks."""

import sys

# --- Batcher's odd-even merge sort network generator ---

def batcher_sort(lo, hi, n, pairs):
    if lo >= hi:
        return
    mid = lo + (hi - lo) // 2
    batcher_sort(lo, mid, n, pairs)
    batcher_sort(mid + 1, hi, n, pairs)
    batcher_merge(lo, hi, 1, n, pairs)

def batcher_merge(lo, hi, step, n, pairs):
    double_step = step * 2
    if double_step > hi - lo:
        if lo < n and lo + step < n:
            pairs.append((lo, lo + step))
        return
    batcher_merge(lo, hi, double_step, n, pairs)
    batcher_merge(lo + step, hi, double_step, n, pairs)
    i = lo + step
    while i + step <= hi:
        if i < n and i + step < n:
            pairs.append((i, i + step))
        i += double_step

def generate_batcher_network(n):
    p = 1
    while p < n:
        p <<= 1
    pairs = []
    batcher_sort(0, p - 1, n, pairs)
    return pairs

# --- Network28 from the paper ---
NETWORK_28_FLAT = [
    0,27, 1,26, 2,25, 3,24, 4,23, 5,22, 6,21, 7,20, 8,9, 10,11, 12,15, 13,14, 16,17, 18,19,
    0,1, 2,3, 4,5, 6,7, 8,10, 9,11, 12,14, 13,15, 16,18, 17,19, 20,21, 22,23, 24,25, 26,27,
    0,2, 1,3, 4,6, 5,7, 8,19, 9,12, 10,14, 11,16, 13,17, 15,18, 20,22, 21,23, 24,26, 25,27,
    0,4, 1,5, 2,20, 3,21, 6,24, 7,25, 8,13, 9,11, 10,17, 12,15, 14,19, 16,18, 22,26, 23,27,
    1,2, 3,24, 4,6, 5,22, 7,20, 8,9, 10,12, 11,13, 14,16, 15,17, 18,19, 21,23, 25,26,
    0,8, 1,4, 2,6, 3,9, 5,7, 10,11, 12,13, 14,15, 16,17, 18,24, 19,27, 20,22, 21,25, 23,26,
    1,10, 2,13, 4,8, 5,12, 6,9, 7,20, 14,25, 15,22, 17,26, 18,21, 19,23,
    3,4, 6,14, 7,11, 8,15, 9,17, 10,18, 12,19, 13,21, 16,20, 23,24,
    2,4, 5,6, 7,8, 9,13, 11,15, 12,16, 14,18, 19,20, 21,22, 23,25,
    2,7, 4,8, 6,10, 9,11, 12,14, 13,15, 16,18, 17,21, 19,23, 20,25,
    1,3, 4,7, 5,6, 8,9, 10,12, 11,16, 13,14, 15,17, 18,19, 20,23, 21,22, 24,26,
    2,3, 4,5, 6,7, 8,10, 9,12, 11,13, 14,16, 15,18, 17,19, 20,21, 22,23, 24,25,
    3,4, 5,6, 7,8, 9,10, 11,12, 13,14, 15,16, 17,18, 19,20, 21,22, 23,24,
]

def get_network28():
    pairs = []
    for i in range(0, len(NETWORK_28_FLAT), 2):
        pairs.append((NETWORK_28_FLAT[i], NETWORK_28_FLAT[i+1]))
    return pairs

def get_network27():
    pairs = []
    for a, b in get_network28():
        if a < 27 and b < 27:
            pairs.append((a, b))
    return pairs

def get_network(n):
    if n == 28:
        return get_network28()
    elif n == 27:
        return get_network27()
    else:
        return generate_batcher_network(n)

# --- Code generation ---

def generate_unrolled_method(n, pairs):
    lines = []
    # Only inline small methods; larger ones can't be inlined anyway
    if n <= 8:
        lines.append(f"    [MethodImpl(MethodImplOptions.AggressiveInlining)]")
    lines.append(f"    private static void Sort{n}(ref int first)")
    lines.append(f"    {{")
    lines.append(f"        int e0 = first;")
    for i in range(1, n):
        lines.append(f"        int e{i} = Unsafe.Add(ref first, {i});")
    lines.append(f"")
    for a, b in pairs:
        lines.append(f"        if (e{a} > e{b}) {{ int temp = e{a}; e{a} = e{b}; e{b} = temp; }}")
    lines.append(f"")
    lines.append(f"        first = e0;")
    for i in range(1, n):
        lines.append(f"        Unsafe.Add(ref first, {i}) = e{i};")
    lines.append(f"    }}")
    return "\n".join(lines)

def generate_file():
    lines = []
    lines.append("using System.Runtime.CompilerServices;")
    lines.append("using System.Runtime.InteropServices;")
    lines.append("")
    lines.append("namespace SortingNetworks;")
    lines.append("")
    lines.append("// <auto-generated>")
    lines.append("// This file was generated by generate_unrolled.py")
    lines.append("// Do not edit manually.")
    lines.append("// </auto-generated>")
    lines.append("")
    lines.append("public static partial class NetworkSort")
    lines.append("{")
    
    for n in [27, 28]:
        pairs = get_network(n)
        lines.append(generate_unrolled_method(n, pairs))
        if n < 28:
            lines.append("")
    
    lines.append("}")
    lines.append("")
    return "\n".join(lines)

if __name__ == "__main__":
    output = generate_file()
    output_path = sys.argv[1] if len(sys.argv) > 1 else "SortingNetworks/NetworkSort.Unrolled.cs"
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(output)
    print(f"Generated {output_path}")
    
    # Print stats
    for n in [27, 28]:
        pairs = get_network(n)
        print(f"  Sort{n}: {len(pairs)} compare-swaps")
