using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SortingNetworks.Generators
{
    /// <summary>
    /// Roslyn incremental source generator that emits sorting network code
    /// for classes decorated with [SortingNetwork(size, typeof(T))].
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public class SortingNetworkGenerator : IIncrementalGenerator
    {
        private const int MinSize = 2;
        private const int MaxSize = 64;

        private static readonly HashSet<string> SupportedTypes = new HashSet<string>
        {
            "byte", "sbyte", "short", "ushort", "int", "uint",
            "long", "ulong", "char", "float", "double",
            "nint", "nuint"
        };

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Register the attribute source so users don't need a separate package
            context.RegisterPostInitializationOutput(ctx =>
            {
                ctx.AddSource("SortingNetworkAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8));
            });

            // Find all class declarations with [SortingNetwork] attributes
            var classDeclarations = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    "SortingNetworks.SortingNetworkAttribute",
                    predicate: static (node, _) => node is ClassDeclarationSyntax,
                    transform: static (ctx, _) => GetGenerationInfo(ctx))
                .Where(static info => info != null)
                .Collect();

            context.RegisterSourceOutput(classDeclarations, static (spc, infos) => Execute(spc, infos!));
        }

        private static GenerationInfo? GetGenerationInfo(GeneratorAttributeSyntaxContext context)
        {
            var classSymbol = (INamedTypeSymbol)context.TargetSymbol;

            var attributes = new List<NetworkRequest>();
            foreach (var attr in context.Attributes)
            {
                if (attr.ConstructorArguments.Length < 2)
                    continue;

                var sizeArg = attr.ConstructorArguments[0];
                var typeArg = attr.ConstructorArguments[1];

                if (sizeArg.Value is int size && typeArg.Value is INamedTypeSymbol typeSymbol)
                {
                    attributes.Add(new NetworkRequest(size, typeSymbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)));
                }
            }

            if (attributes.Count == 0)
                return null;

            var namespaceName = classSymbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : classSymbol.ContainingNamespace.ToDisplayString();

            return new GenerationInfo(
                classSymbol.Name,
                namespaceName,
                attributes.ToArray());
        }

        private static void Execute(SourceProductionContext context, ImmutableArray<GenerationInfo?> infos)
        {
            foreach (var info in infos)
            {
                if (info == null) continue;
                var source = GenerateSource(context, info);
                if (source != null)
                {
                    context.AddSource($"{info.ClassName}.g.cs", SourceText.From(source, Encoding.UTF8));
                }
            }
        }

        private static string? GenerateSource(SourceProductionContext context, GenerationInfo info)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            if (info.Namespace != null)
            {
                sb.AppendLine($"namespace {info.Namespace}");
                sb.AppendLine("{");
            }

            sb.AppendLine($"    partial class {info.ClassName}");
            sb.AppendLine("    {");

            bool anyGenerated = false;
            foreach (var request in info.Requests)
            {
                if (request.Size < MinSize || request.Size > MaxSize)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticDescriptors.InvalidSize, Location.None, request.Size, MinSize, MaxSize));
                    continue;
                }

                if (!SupportedTypes.Contains(request.TypeName))
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticDescriptors.UnsupportedType, Location.None, request.TypeName));
                    continue;
                }

                // Get the network (from database or Batcher)
                var network = NetworkDatabase.GetNetwork(request.Size);
                if (network == null)
                {
                    network = BatcherNetworkBuilder.Generate(request.Size);
                }

                // Emit the public Sort method with scalar path
                // TODO: Add SIMD dispatch when SimdX86Emitter is stable
                sb.AppendLine($"        /// <summary>Sorts exactly {request.Size} elements of type {request.TypeName} using an optimal sorting network.</summary>");
                sb.AppendLine($"        public static void Sort{request.Size}(System.Span<{request.TypeName}> span)");
                sb.AppendLine("        {");
                sb.AppendLine($"            if (span.Length != {request.Size})");
                sb.AppendLine($"                throw new System.ArgumentException($\"Span must have exactly {request.Size} elements, but was {{span.Length}}.\", nameof(span));");
                sb.AppendLine($"            SortScalar{request.Size}(span);");
                sb.AppendLine("        }");
                sb.AppendLine();

                // Emit the scalar implementation
                sb.Append(ScalarEmitter.EmitSortMethod(request.Size, request.TypeName, network));
                sb.AppendLine();
                anyGenerated = true;
            }

            sb.AppendLine("    }");

            if (info.Namespace != null)
            {
                sb.AppendLine("}");
            }

            return anyGenerated ? sb.ToString() : null;
        }

        private const string AttributeSource = @"// <auto-generated />
#nullable enable

namespace SortingNetworks
{
    /// <summary>
    /// Marks a partial class for sorting network code generation.
    /// The source generator will emit a Sort method that uses an optimal
    /// sorting network for the specified size and type.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
    internal sealed class SortingNetworkAttribute : System.Attribute
    {
        public int Size { get; }
        public System.Type ElementType { get; }

        public SortingNetworkAttribute(int size, System.Type elementType)
        {
            Size = size;
            ElementType = elementType;
        }
    }
}
";

        private sealed class GenerationInfo
        {
            public string ClassName { get; }
            public string? Namespace { get; }
            public NetworkRequest[] Requests { get; }

            public GenerationInfo(string className, string? ns, NetworkRequest[] requests)
            {
                ClassName = className;
                Namespace = ns;
                Requests = requests;
            }
        }

        private sealed class NetworkRequest
        {
            public int Size { get; }
            public string TypeName { get; }

            public NetworkRequest(int size, string typeName)
            {
                Size = size;
                TypeName = typeName;
            }
        }
    }
}
