using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SortingNetworks.Generators
{
    /// <summary>
    /// Roslyn incremental source generator that emits sorting network code
    /// for classes decorated with [SortingNetwork(size, typeof(T))].
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public class SortingNetworkGenerator : IIncrementalGenerator
    {
        private const int MinSize = 2;
        private const int MaxSize = 64;

        private static readonly HashSet<string> SupportedTypes = new HashSet<string>
        {
            "byte", "sbyte", "short", "ushort", "int", "uint",
            "long", "ulong", "char", "float", "double",
            "nint", "nuint"
        };

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Register the attribute source so users don't need a separate package
            context.RegisterPostInitializationOutput(ctx =>
            {
                ctx.AddSource("SortingNetworkAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8));
            });

            // Find all class declarations with [SortingNetwork] attributes
            var classDeclarations = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    "SortingNetworks.SortingNetworkAttribute",
                    predicate: static (node, _) => node is ClassDeclarationSyntax,
                    transform: static (ctx, _) => GetGenerationInfo(ctx))
                .Where(static info => info != null)
                .Collect();

            context.RegisterSourceOutput(classDeclarations, static (spc, infos) => Execute(spc, infos!));
        }

        private static GenerationInfo? GetGenerationInfo(GeneratorAttributeSyntaxContext context)
        {
            var classSymbol = (INamedTypeSymbol)context.TargetSymbol;

            var attributes = new List<NetworkRequest>();
            foreach (var attr in context.Attributes)
            {
                if (attr.ConstructorArguments.Length < 2)
                    continue;

                var sizeArg = attr.ConstructorArguments[0];
                var typeArg = attr.ConstructorArguments[1];

                if (sizeArg.Value is int size && typeArg.Value is INamedTypeSymbol typeSymbol)
                {
                    attributes.Add(new NetworkRequest(size, typeSymbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)));
                }
            }

            if (attributes.Count == 0)
                return null;

            var namespaceName = classSymbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : classSymbol.ContainingNamespace.ToDisplayString();

            return new GenerationInfo(
                classSymbol.Name,
                namespaceName,
                attributes.ToArray());
        }

        private static void Execute(SourceProductionContext context, ImmutableArray<GenerationInfo?> infos)
        {
            foreach (var info in infos)
            {
                if (info == null) continue;
                var source = GenerateSource(context, info);
                if (source != null)
                {
                    context.AddSource($"{info.ClassName}.g.cs", SourceText.From(source, Encoding.UTF8));
                }
            }
        }

        private static string? GenerateSource(SourceProductionContext context, GenerationInfo info)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            // Validate all requests and collect valid ones, grouped by type
            var validRequests = new List<NetworkRequest>();
            foreach (var request in info.Requests)
            {
                if (request.Size < MinSize || request.Size > MaxSize)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticDescriptors.InvalidSize, Location.None, request.Size, MinSize, MaxSize));
                    continue;
                }

                if (!SupportedTypes.Contains(request.TypeName))
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticDescriptors.UnsupportedType, Location.None, request.TypeName));
                    continue;
                }

                validRequests.Add(request);
            }

            if (validRequests.Count == 0)
                return null;

            // Check if any request will use SIMD
            bool needsSimdUsing = false;
            foreach (var request in validRequests)
            {
                if (SimdX86Emitter.CanEmit(request.TypeName, request.Size))
                {
                    needsSimdUsing = true;
                    break;
                }
            }
            if (needsSimdUsing)
            {
                sb.AppendLine("using System.Runtime.Intrinsics;");
                sb.AppendLine();
            }

            if (info.Namespace != null)
            {
                sb.AppendLine($"namespace {info.Namespace}");
                sb.AppendLine("{");
            }

            sb.AppendLine($"    partial class {info.ClassName}");
            sb.AppendLine("    {");

            // Group requests by type to emit one public Sort(Span<T>) per type
            var byType = new Dictionary<string, List<NetworkRequest>>();
            foreach (var request in validRequests)
            {
                if (!byType.TryGetValue(request.TypeName, out var list))
                {
                    list = new List<NetworkRequest>();
                    byType[request.TypeName] = list;
                }
                list.Add(request);
            }

            // Pre-compute networks and SIMD info for each request
            var networksByRequest = new Dictionary<string, int[]>();
            var simdStepsByRequest = new Dictionary<string, List<List<(int A, int B)>>>();
            foreach (var request in validRequests)
            {
                var key = $"{request.TypeName}_{request.Size}";
                var network = NetworkDatabase.GetNetwork(request.Size);
                if (network == null)
                {
                    network = BatcherNetworkBuilder.Generate(request.Size);
                }
                networksByRequest[key] = network;

                if (SimdX86Emitter.CanEmit(request.TypeName, request.Size))
                {
                    simdStepsByRequest[key] = SimdX86Emitter.DecomposeIntoSteps(network);
                }
            }

            // Emit one public Sort overload per type with flattened dispatch
            // Pattern matches the library: SIMD check → scalar fallback, all inline
            foreach (var kvp in byType)
            {
                var typeName = kvp.Key;
                var sizes = kvp.Value;
                sizes.Sort((a, b) => a.Size.CompareTo(b.Size));

                // Check which sizes have SIMD support
                var simdSizes = new List<NetworkRequest>();
                foreach (var request in sizes)
                {
                    var key = $"{request.TypeName}_{request.Size}";
                    if (simdStepsByRequest.ContainsKey(key))
                        simdSizes.Add(request);
                }

                // Determine the SIMD guard condition string
                string? simdGuard = null;
                if (simdSizes.Count > 0)
                {
                    simdGuard = SimdX86Emitter.GetGuardCondition(typeName);
                }

                sb.AppendLine($"        /// <summary>Sorts a span of {typeName} using an optimal sorting network based on span length.</summary>");
                sb.AppendLine($"        public static void Sort(System.Span<{typeName}> span)");
                sb.AppendLine("        {");
                sb.AppendLine("            int n = span.Length;");

                // Build the size check condition
                var sizeChecks = string.Join(" || ", sizes.Select(s => $"n == {s.Size}"));
                sb.AppendLine($"            if ({sizeChecks})");
                sb.AppendLine("            {");

                // SIMD dispatch block (if any sizes support SIMD)
                if (simdGuard != null && simdSizes.Count > 0)
                {
                    sb.AppendLine($"                if ({simdGuard})");
                    sb.AppendLine("                {");
                    if (simdSizes.Count == 1)
                    {
                        // Single SIMD size: guard by length check
                        sb.AppendLine($"                    if (n == {simdSizes[0].Size})");
                        sb.AppendLine("                    {");
                        sb.AppendLine($"                        SortSimd{simdSizes[0].Size}_{typeName}(span);");
                        sb.AppendLine("                        return;");
                        sb.AppendLine("                    }");
                    }
                    else
                    {
                        foreach (var request in simdSizes)
                        {
                            sb.AppendLine($"                    if (n == {request.Size}) {{ SortSimd{request.Size}_{typeName}(span); return; }}");
                        }
                    }
                    sb.AppendLine("                }");
                }

                // Scalar fallback: get ref and dispatch
                sb.AppendLine($"                ref {typeName} first = ref System.Runtime.InteropServices.MemoryMarshal.GetReference(span);");
                if (sizes.Count == 1)
                {
                    sb.AppendLine($"                Sort{sizes[0].Size}(ref first);");
                }
                else
                {
                    foreach (var request in sizes)
                    {
                        sb.AppendLine($"                if (n == {request.Size}) {{ Sort{request.Size}(ref first); return; }}");
                    }
                }
                sb.AppendLine("                return;");
                sb.AppendLine("            }");
                sb.AppendLine($"            throw new System.ArgumentException($\"No sorting network for length {{n}}. Supported lengths: {string.Join(", ", sizes.Select(s => s.Size.ToString()))}.\", nameof(span));");
                sb.AppendLine("        }");
                sb.AppendLine();
            }

            // Emit private SIMD methods and scalar Sort{size} methods
            foreach (var request in validRequests)
            {
                var key = $"{request.TypeName}_{request.Size}";
                var network = networksByRequest[key];

                // Emit SIMD method if applicable
                if (simdStepsByRequest.TryGetValue(key, out var simdSteps))
                {
                    var (simdMethod, _) = SimdX86Emitter.Emit(request.Size, request.TypeName, simdSteps);
                    if (!string.IsNullOrEmpty(simdMethod))
                    {
                        sb.AppendLine(simdMethod);
                        sb.AppendLine();
                    }
                }

                // Emit scalar method (takes ref T first, matches library pattern)
                sb.Append(ScalarEmitter.EmitSortMethod(request.Size, request.TypeName, network));
                sb.AppendLine();
            }

            sb.AppendLine("    }");

            if (info.Namespace != null)
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private const string AttributeSource = @"// <auto-generated />
#nullable enable

namespace SortingNetworks
{
    /// <summary>
    /// Marks a partial class for sorting network code generation.
    /// The source generator will emit a Sort method that uses an optimal
    /// sorting network for the specified size and type.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
    internal sealed class SortingNetworkAttribute : System.Attribute
    {
        public int Size { get; }
        public System.Type ElementType { get; }

        public SortingNetworkAttribute(int size, System.Type elementType)
        {
            Size = size;
            ElementType = elementType;
        }
    }
}
";

        private sealed class GenerationInfo
        {
            public string ClassName { get; }
            public string? Namespace { get; }
            public NetworkRequest[] Requests { get; }

            public GenerationInfo(string className, string? ns, NetworkRequest[] requests)
            {
                ClassName = className;
                Namespace = ns;
                Requests = requests;
            }
        }

        private sealed class NetworkRequest
        {
            public int Size { get; }
            public string TypeName { get; }

            public NetworkRequest(int size, string typeName)
            {
                Size = size;
                TypeName = typeName;
            }
        }
    }
}
